CREATE TABLE IF NOT EXISTS {full_table_name} (
    row_id                     VARCHAR,
    order_id                   VARCHAR,
    order_date                 DATE,
    ship_date                  DATE,
    shipping_days              INTEGER,
    order_year                 INTEGER,
    order_month                INTEGER,
    order_quarter              INTEGER,
    order_day_of_week          VARCHAR,
    ship_mode                  VARCHAR,
    customer_id                VARCHAR,
    customer_name              VARCHAR,
    segment                    VARCHAR,
    country                    VARCHAR,
    city                       VARCHAR,
    governorate                VARCHAR,
    postal_code                VARCHAR,
    region                     VARCHAR,
    product_id                 VARCHAR,
    category                   VARCHAR,
    sub_category               VARCHAR,
    product_name               VARCHAR,
    sales                      DECIMAL(10,2),
    quantity                   INTEGER,
    discount                   DECIMAL(5,2),
    profit                     DECIMAL(10,2),
    unit_price                 DECIMAL(10,4),
    profit_margin              DECIMAL(10,4),
    discount_amount            DECIMAL(10,2),
    profit_status              VARCHAR,
    order_value_tier           VARCHAR,
    ship_mode_priority         INTEGER,
    has_missing_financial_data BOOLEAN,
    is_invalid_ship_date       BOOLEAN,
    updated_at                 TIMESTAMP,
    load_date                  DATE
);

ALTER TABLE {full_table_name}
SET PARTITIONED BY (order_year, order_month);